version: '3'
services:
  app_proxy:
    environment:
      APP_HOST: jdownloader_server_1
      APP_PORT: 5800
    container_name: jdownloader_app_proxy_1
  Server:
    image: jlesage/jdownloader-2
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5800:5800"
    volumes:
      - "${APP_DATA_DIR}/data/config:/config:rw"
      - "/mnt/root/media/hd-1-tera:/hd-1-tera"
    shm_size: 1gb
    container_name: jdownloader_server_1
