version: "3.8"

services:
  app_proxy:
    environment:
      - TZ=${TZ:-UTC} # Timezone, ajuste para sua localização
      - USER_ID=1000 # Altere para o ID do usuário no host
      - GROUP_ID=1000 # Altere para o ID do grupo no host
      - DISPLAY_WIDTH=1280 # Resolução da interface remota
      - DISPLAY_HEIGHT=720
      - KEEP_APP_RUNNING=1 # Mantém o aplicativo sempre em execução
      - XDG_DOWNLOAD_DIR=/downloads
  server:
    image: jlesage/jdownloader-2:latest
    container_name: my-tool-jdownloader2
    ports:
      - "5800:5800" # Porta para acessar a interface remota
    volumes:
      - ./data:/config:rw # Dados de configuração do app
      - ./downloads:/downloads:rw # Diretório para downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5800"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - umbrel_default
networks:
  umbrel_default:
    external: true
