version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: my-tool-jdownloader2_1
      APP_PORT: 5800
    container_name: my-tool-jdownloader2_app_proxy_1
  server:
    image: jlesage/jdownloader-2
    user: '1000:1000'
    restart: on-failure
    init: true
    volumes:
		- "${APP_DATA_DIR}/docker/appdata/jdownloader-2:/config:rw"
		- /mnt/root/media/hd-1-tera:/data/hd-1-tera
    container_name: my-tool-jdownloader2_server_1
