version: '3'
services:
  server:
    image: jlesage/jdownloader-2
    hostname: ${DEVICE_HOSTNAME}
    ports:
     - 5800:5800
    volumes:
     - "${APP_DATA_DIR}/data/config:/config:rw"
     - "/mnt/root/media/hd-1-tera:/data/hd-1-tera"
    container_name: departure-jdownloader2_server_1
