version: '3.7'
services:
  server:
    image: jlesage/jdownloader-2
    restart: on-failure
    hostname: ${DEVICE_HOSTNAME}
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
     - "${APP_DATA_DIR}/data/config:/config:rw"
     - "/mnt/root/media/hd-1-tera:/data/hd-1-tera"
    ports:
     - 5800:5800
    container_name: departure-jdownloader2_server_1
